### ISSUE TITLE
0.2.0 tag/release not found

### ISSUE THREAD

**Issue by andreasstieger** [shibatch/oomstaller#2]
Hi there, on 2024-11-18 you announced a 0.2.0 at http://freshcode.club/projects/oomstaller pointing at `HEAD`, but there is no corresponding tag or release.

**Comment by andreasstieger** [comment]
Thanks, fixed in [0.2.0](https://github.com/shibatch/oomstaller/releases/tag/0.2.0)

I believe the tool will have a niche usage, but in that niche may solve a particular problem. If you are looking for more exposure and feedback, maybe blog about a practical example with a specifically large build.

**Comment by shibatch** [comment]
Thank you for your suggestion!
